# Generated by Django 5.2.3 on 2025-06-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['symbol', 'event_time'], name='tickers_tic_symbol_840df6_idx')],
            },
        ),
    ]
